### ISSUE TITLE
モダンなヘッダーを作成する

### ISSUE THREAD

**Issue by atsushimemet** [atsushimemet/vook_web_v1#3]
# Todo
## Main
- [x] bootstrapで実現可能か確認
- [x] headにbootstrapのcdnを配置
- [x] Navbarを配置、表示確認
- [x] Navbarを"Vook"に変更
- [x] Homeと同じコンポーネントを"About/商品検索/記事/コミュニティ"それぞれで準備
  - [x] Link/Dropdown/DisableをHomeコンポーネントに変更
  - [x] Homeを"About/商品検索/記事/コミュニティ"に変更
- [x] ログイン/新規登録を準備
  - [x] Searchのフォームを削除
  - [x] Searchボタンを2つ配置
  - [x] ログイン/新規登録ボタンを準備
  - [x] 二つのボタンの間隔を調整
## Other
- [x] cssディレクトリの作成
- [x] main.cssの作成
